### ISSUE TITLE
What has actually been modified in this repository from the original?

### ISSUE THREAD

**Issue by fpf3** [poopgiggle/prudebug#1]
I ask this because I want to know if you have made any improvements or changes. For instance, I'm led to believe that prudebug v0.24 doesn't properly support features added in PRUSS v2.

**Comment by poopgiggle** [comment]
I haven't. I ended up doing what I needed to do with the PRU and abandoned this.

Mostly I just wanted people to have a place to get this project from other than SourceForge.

**Comment by fpf3** [comment]
Okay, thanks for responding.
